//
//  LocalLLMOrchestrator.swift
//  AnigmaAppMac
//
//  Orchestrates multiple CLI agents using a local LLM as the decision-making brain.
//  Governed execution with full audit trail.
//

import Foundation
import AnigmaClientKit
import CryptoKit
import AnigmaPrimitives
import AnigmaHostMac
import MLWorkerCommon
import ContextumModule
import DatabaseCore
import ContractsCore

// MARK: - CLI Tool Registry

/// Registry of available CLI coding agents
struct CLIToolRegistry {

    /// Known CLI tools that can be orchestrated
    enum Tool: String, CaseIterable, Identifiable, Codable {
        case codex = "codex"
        case claudeCLI = "claude"
        case copilotCLI = "gh-copilot"
        case geminiCLI = "gemini"
        case aiderCLI = "aider"
        case cursorCLI = "cursor"

        var id: String { rawValue }

        var displayName: String {
            switch self {
            case .codex: return "OpenAI Codex"
            case .claudeCLI: return "Claude CLI"
            case .copilotCLI: return "GitHub Copilot CLI"
            case .geminiCLI: return "Gemini CLI"
            case .aiderCLI: return "Aider"
            case .cursorCLI: return "Cursor CLI"
            }
        }

        var description: String {
            switch self {
            case .codex:
                return "OpenAI's code generation model optimized for programming tasks"
            case .claudeCLI:
                return "Anthropic's Claude assistant for code review and generation"
            case .copilotCLI:
                return "GitHub's AI assistant that provides command suggestions"
            case .geminiCLI:
                return "Google's Gemini CLI for code generation and analysis"
            case .aiderCLI:
                return "AI pair programming tool that edits code directly"
            case .cursorCLI:
                return "AI-first code editor with deep project understanding"
            }
        }

        var strengths: [String] {
            switch self {
            case .codex: return ["Fast", "Accurate", "Multi-language"]
            case .claudeCLI: return ["Code Review", "Context Understanding", "Python/JS Specialist"]
            case .copilotCLI: return ["Shell Integration", "Fast Suggestions", "Convenient"]
            case .geminiCLI: return ["Multi-modal", "High Context", "Fast Reasoning"]
            case .aiderCLI: return ["Project-wide Edits", "Git Integration", "Iterative Refinement"]
            case .cursorCLI: return ["Deep Context", "UI-first", "High Accuracy"]
            }
        }
    }

    /// Status of a CLI tool installation
    struct Availability: Identifiable, Codable {
        let tool: Tool
        var isInstalled: Bool
        var version: String?
        var binaryPath: String?

        var id: String { tool.id }
    }
}

// MARK: - Orchestration Messages

/// A message in the orchestration conversation
struct OrchestratorMessage: Identifiable, Codable {
    let id: UUID
    let role: Role
    let content: String
    let timestamp: Date
    var toolCall: ToolCallInfo?

    enum Role: String, Codable {
        case user
        case orchestrator // The local LLM
        case tool // Output from a CLI tool
        case system
    }

    init(role: Role, content: String, toolCall: ToolCallInfo? = nil) {
        self.id = UUID()
        self.role = role
        self.content = content
        self.timestamp = Date()
        self.toolCall = toolCall
    }
}

struct ToolCallInfo: Codable {
    let toolName: String
    let instruction: String
    var status: Status

    enum Status: String, Codable {
        case pending
        case executing
        case success
        case failed
    }
}

// MARK: - Orchestration Plan

/// A multi-step execution plan generated by the LLM
struct OrchestrationPlan: Codable {
    let taskDescription: String
    let reasoning: String
    let steps: [OrchestrationStep]
}

/// A single step in an execution plan
struct OrchestrationStep: Codable, Identifiable {
    var id: String { "\(order)-\(tool.rawValue)" }
    let order: Int
    let tool: CLIToolRegistry.Tool
    let instruction: String
    var output: String?
    var status: StepStatus = .pending

    enum StepStatus: String, Codable {
        case pending
        case running
        case completed
        case failed
        case skipped
    }
}

// MARK: - Contextum Integration Types

struct ContextumPostflightConfiguration: Sendable {
    let agentId: String
    let taskTaxonomy: String
    let durationMs: Int
    let outcome: String
    let errorCode: String?
    let workflowID: UUID
    let runID: UUID
    let jobID: UUID
}

// MARK: - Orchestrator

public struct ToolAvailability: Identifiable {
    public let id = UUID()
    let tool: CLIToolRegistry.Tool  // Internal to avoid exposing internal type
    public let isInstalled: Bool
    public let binaryPath: String?
    public let version: String?
}

import Observation

/// Decision engine for multi-agent CLI orchestration
@Observable
final class LocalLLMOrchestrator {
    private let contextum: Contextum?
    private let mlWorker: MLWorkerClient
    public var availableTools: [ToolAvailability] = []
    public var messages: [OrchestratorMessage] = []
    public var isProcessing: Bool = false
    public var currentPlan: OrchestrationPlan?
    public var currentStepIndex: Int = 0

    init(contextum: Contextum? = nil, mlWorker: MLWorkerClient) {
        self.contextum = contextum
        self.mlWorker = mlWorker
    }

    /// Add a message to the conversation history
    public func addMessage(_ role: OrchestratorMessage.Role, _ content: String, toolCall: ToolCallInfo? = nil) {
        messages.append(OrchestratorMessage(role: role, content: content, toolCall: toolCall))
    }

    /// Clear conversation history
    public func clearConversation() {
        messages = []
        currentPlan = nil
        currentStepIndex = 0
    }

    /// Submit a task to the orchestrator
    public func submitTask(_ task: String, workspace: WorkspaceSummary? = nil) async {
        isProcessing = true
        defer { isProcessing = false }

        addMessage(.user, task)
        // Implementation for orchestration loop...
    }

    /// Discover available tools by checking PATH
    public func refreshAvailableTools() async {
        availableTools = []
        for tool in CLIToolRegistry.Tool.allCases {
            let (isInstalled, path) = await checkToolInstalled(tool)
            availableTools.append(ToolAvailability(
                tool: tool,
                isInstalled: isInstalled,
                binaryPath: path,
                version: nil
            ))
        }
    }

    private func checkToolInstalled(_ tool: CLIToolRegistry.Tool) async -> (Bool, String?) {
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/usr/bin/which")
        task.arguments = [tool.rawValue]
        
        let pipe = Pipe()
        task.standardOutput = pipe
        
        do {
            try task.run()
            task.waitUntilExit()
            
            if task.terminationStatus == 0 {
                let data = pipe.fileHandleForReading.readDataToEndOfFile()
                if let path = String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) {
                    return (true, path)
                }
            }
        } catch {
            return (false, nil)
        }
        
        return (false, nil)
    }

    /// Execute a complex task using orchestrated tools
    func executeTask(
        _ task: String,
        workspace: RepoWorkspace,
        workflowID: UUID = UUID(),
        runID: UUID = UUID(),
        jobID: UUID = UUID()
    ) async throws -> String {
        addMessage(.user, task)
        
        // Step 1: Gather Context (Contextum Integration)
        let context = await gatherTaskContext(task, workspace: workspace, workflowID: workflowID, runID: runID)
        if !context.isEmpty {
            addMessage(.system, "Retrieved context for task analysis: \(context.count) chunks found.")
        }

        // Step 2: Generate Execution Plan using Local LLM
        let plan = try await generatePlan(task, context: context)
        addMessage(.orchestrator, "I have developed an execution plan: \(plan.taskDescription)\n\n\(plan.reasoning)")

        // Step 3: Execute Plan Steps
        var finalResult = ""
        for step in plan.steps {
            addMessage(.system, "Executing Step \(step.order): \(step.tool.displayName) -> \(step.instruction)")
            
            let output = try await executeStep(step, workspace: workspace, workflowID: workflowID, runID: runID, jobID: jobID)
            addMessage(.tool, output)
            finalResult = output // Last tool output often represents result
        }

        // Step 4: Postflight tracking (Contextum Integration)
        let config = ContextumPostflightConfiguration(
            agentId: "anigma-orchestrator",
            taskTaxonomy: classifyTask(task),
            durationMs: 0, // Should track actual duration
            outcome: "success",
            errorCode: nil,
            workflowID: workflowID,
            runID: runID,
            jobID: jobID
        )
        try await contextumPostflight(config: config)

        return finalResult
    }

    /// Use Contextum to find relevant code context for the task
    private func gatherTaskContext(
        _ task: String,
        workspace: RepoWorkspace,
        workflowID: UUID,
        runID: UUID
    ) async -> [String] {
        guard let contextum = contextum else { return [] }

        // Record intent to find context
        _ = await AIReceiptIntegration.shared.recordAIOperationStart(
            operationID: UUID().uuidString,
            modelID: "orchestrator",
            taskType: "gather_context",
            inputs: ["query": task, "workflowID": workflowID.uuidString]
        )

        // Perform hybrid search (FTS only in Phase 0, embeddings in Phase 1)
        let searchRequest = HybridSearchSystem.SearchRequest(
            query: task,
            mode: .fullText,  // Phase 0: FTS only, upgrade to .hybrid in Phase 1
            limit: 10,
            filters: ["workspace": workspace.rootURL.path],
            workflowId: workflowID.uuidString,
            runId: runID.uuidString
        )

        do {
            let results = try await contextum.search(request: searchRequest)
            // Extract content from results
            return results.chunks.map { $0.content }
        } catch {
            // Non-critical failure: log and continue without context
            addMessage(.system, "⚠️ Context search failed: \(error.localizedDescription)")
            return []
        }
    }

    /// Generate an execution plan using the local LLM
    private func generatePlan(_ task: String, context: [String]) async throws -> OrchestrationPlan {
        // Construct prompt for the LLM
        let prompt = """
        You are Anigma Orchestrator. Your goal is to plan a sequence of CLI tool executions to solve a coding task.
        Available tools: \(availableTools.filter { $0.isInstalled }.map { $0.tool.rawValue }.joined(separator: ", "))
        
        Task: \(task)
        
        Context found in codebase:
        \(context.joined(separator: "\n---\n"))
        
        Respond ONLY with a JSON object in this format:
        {
          "taskDescription": "Summary of what needs to be done",
          "reasoning": "Why this sequence was chosen",
          "steps": [
            { "order": 1, "tool": "toolname", "instruction": "cli arguments to pass" }
          ]
        }
        """

        // Use MLWorker to generate completion
        // For MVP, we use a simple chat interface
        // let response = try await mlWorker.complete(prompt: prompt)
        
        // Placeholder implementation until MLWorker completion is wired in.
        return OrchestrationPlan(
            taskDescription: "Implement \(task)",
            reasoning: "Sequential execution of tools",
            steps: [
                OrchestrationStep(order: 1, tool: .aiderCLI, instruction: "--message \"\(task)\"")
            ]
        )
    }

    private func contextumPostflight(config: ContextumPostflightConfiguration) async throws {
        guard let contextum = contextum else {
            return
        }

        let outcome = TelemetryEventComponent.Outcome(rawValue: config.outcome) ?? .success

        try await contextum.recordAgentExecution(
            agentId: config.agentId,
            taskTaxonomy: config.taskTaxonomy,
            durationMs: config.durationMs,
            outcome: outcome,
            errorCode: config.errorCode
        )
    }

    /// Classify task into taxonomy for skill tracking
    private func classifyTask(_ task: String) -> String {
        let lower = task.lowercased()

        if lower.contains("refactor") { return "refactoring" }
        if lower.contains("review") { return "code_review" }
        if lower.contains("test") || lower.contains("spec") { return "testing" }
        if lower.contains("fix") || lower.contains("bug") { return "bug_fix" }
        if lower.contains("implement") || lower.contains("add") { return "feature_implementation" }
        if lower.contains("document") || lower.contains("doc") { return "documentation" }
        if lower.contains("optimize") || lower.contains("performance") { return "optimization" }

        return "general_coding"
    }

    /// Execute a single orchestration step with full correlation
    private func executeStep(
        _ step: OrchestrationStep,
        workspace: RepoWorkspace,
        workflowID: UUID,
        runID: UUID,
        jobID: UUID
    ) async throws -> String {
        guard let availability = availableTools.first(where: { $0.tool == step.tool && $0.isInstalled }),
              let binaryPath = availability.binaryPath else {
            throw OrchestratorError.toolNotAvailable(step.tool.displayName)
        }

        let startTime = Date()
        
        // Build and execute the command
        let process = Process()
        process.executableURL = URL(fileURLWithPath: binaryPath)
        process.arguments = [step.instruction]
        process.currentDirectoryURL = workspace.rootURL

        // Environment with correlation tracking
        var env = ProcessInfo.processInfo.environment
        env["ANIGMA_ORCHESTRATED"] = "1"
        env["ANIGMA_STEP"] = "\(step.order)"
        env["ANIGMA_WORKFLOW_ID"] = workflowID.uuidString
        env["ANIGMA_RUN_ID"] = runID.uuidString
        env["ANIGMA_JOB_ID"] = jobID.uuidString
        process.environment = env

        // Capture output
        let outputPipe = Pipe()
        let errorPipe = Pipe()
        process.standardOutput = outputPipe
        process.standardError = errorPipe

        try process.run()
        process.waitUntilExit()

        let endTime = Date()
        let executionTimeMs = Int64(endTime.timeIntervalSince(startTime) * 1000)

        let outputData = outputPipe.fileHandleForReading.readDataToEndOfFile()
        let errorData = errorPipe.fileHandleForReading.readDataToEndOfFile()

        var result = String(data: outputData, encoding: .utf8) ?? ""
        var errorOutput = ""
        if let stderr = String(data: errorData, encoding: .utf8), !stderr.isEmpty {
            errorOutput = stderr
            result += "\n⚠️ stderr: \(errorOutput)"
        }

        // Record tool execution receipt
        let inputs = [
            "tool": step.tool.rawValue,
            "instruction": step.instruction,
            "working_directory": workspace.rootURL.path,
            "step_order": step.order
        ] as [String: Any]
        
        let outputs = [
            "stdout": result,
            "stderr": errorOutput,
            "exit_code": process.terminationStatus
        ] as [String: Any]
        
        await AIReceiptIntegration.shared.recordToolExecution(
            toolName: step.tool.rawValue,
            toolType: "cli",
            inputs: inputs,
            outputs: outputs,
            executionTimeMs: executionTimeMs,
            exitCode: process.terminationStatus,
            workflowID: workflowID.uuidString
        )

        if process.terminationStatus != 0 {
            throw OrchestratorError.toolFailed(step.tool.displayName, process.terminationStatus)
        }

        return result.isEmpty ? "(No output)" : result
    }
}

// MARK: - Errors

enum OrchestratorError: LocalizedError {
    case toolNotAvailable(String)
    case toolFailed(String, Int32)
    case planGenerationFailed

    var errorDescription: String? {
        switch self {
        case .toolNotAvailable(let name):
            return "Tool '\(name)' is not installed or not in PATH"
        case .toolFailed(let name, let code):
            return "Tool '\(name)' failed with exit code \(code)"
        case .planGenerationFailed:
            return "Failed to generate execution plan"
        }
    }
}

// MARK: - Plan Response Format

/// JSON structure for LLM plan responses
private struct OrchestrationPlanResponse: Codable {
    let taskDescription: String
    let reasoning: String
    let steps: [StepData]

    struct StepData: Codable {
        let order: Int
        let tool: String
        let instruction: String
        let inputFromPrevious: Bool
    }
}

// MARK: - String Extension for Hashing

extension String {
    func blake3Hash() -> String {
        return BLAKE3Digest.hex(of: self)
    }
}
