//
//  PostgresCutoverUtility.swift
//  DatabaseCore
//
//  PostgreSQL cutover exporter for legacy row stores.
//

import Foundation

public struct PostgresCutoverColumn: Codable, Sendable, Equatable {
    public let name: String
    public let sourceType: String?
    public let postgresType: String
    public let isPrimaryKey: Bool
    public let isNotNull: Bool
    public let defaultValue: String?

    public init(
        name: String,
        sourceType: String?,
        postgresType: String,
        isPrimaryKey: Bool,
        isNotNull: Bool,
        defaultValue: String?
    ) {
        self.name = name
        self.sourceType = sourceType
        self.postgresType = postgresType
        self.isPrimaryKey = isPrimaryKey
        self.isNotNull = isNotNull
        self.defaultValue = defaultValue
    }
}

public struct PostgresCutoverTable: Codable, Sendable, Equatable {
    public let name: String
    public let rowCount: Int
    public let columns: [PostgresCutoverColumn]

    public init(
        name: String,
        rowCount: Int,
        columns: [PostgresCutoverColumn]
    ) {
        self.name = name
        self.rowCount = rowCount
        self.columns = columns
    }

    public var createTableSQL: String {
        let compositePrimaryKey = columns.filter(\.isPrimaryKey).count > 1
        let columnLines = columns.map { column -> String in
            if column.isPrimaryKey && !compositePrimaryKey && Self.normalizedSourceType(column.sourceType) == "INTEGER" {
                return "\(Self.quoteIdentifier(column.name)) BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            }

            var fragments: [String] = ["\(Self.quoteIdentifier(column.name)) \(column.postgresType)"]
            if column.isPrimaryKey && !compositePrimaryKey {
                fragments.append("PRIMARY KEY")
            }
            if column.isNotNull {
                fragments.append("NOT NULL")
            }
            if let defaultValue = column.defaultValue {
                fragments.append("DEFAULT \(defaultValue)")
            }
            return fragments.joined(separator: " ")
        }

        let pkClause: String
        if compositePrimaryKey {
            pkClause = ",\n    PRIMARY KEY (\(columns.filter(\.isPrimaryKey).map { Self.quoteIdentifier($0.name) }.joined(separator: ", ")))"
        } else {
            pkClause = ""
        }

        return """
        CREATE TABLE IF NOT EXISTS \(Self.quoteIdentifier(name)) (
            \(columnLines.joined(separator: ",\n    "))\(pkClause)
        );
        """
    }

    private static func normalizedSourceType(_ type: String?) -> String {
        type?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .uppercased() ?? ""
    }

    private static func quoteIdentifier(_ identifier: String) -> String {
        "\"\(identifier.replacingOccurrences(of: "\"", with: "\"\""))\""
    }
}

public struct PostgresCutoverManifest: Codable, Sendable, Equatable {
    public let sourcePath: String
    public let generatedAt: Date
    public let totalRows: Int
    public let tables: [PostgresCutoverTable]

    public init(
        sourcePath: String,
        generatedAt: Date,
        totalRows: Int,
        tables: [PostgresCutoverTable]
    ) {
        self.sourcePath = sourcePath
        self.generatedAt = generatedAt
        self.totalRows = totalRows
        self.tables = tables
    }
}

public struct PostgresCutoverBundle: Codable, Sendable, Equatable {
    public let manifest: PostgresCutoverManifest
    public let postgresScript: String

    public init(manifest: PostgresCutoverManifest, postgresScript: String) {
        self.manifest = manifest
        self.postgresScript = postgresScript
    }
}

public enum PostgresCutoverUtility {
    /// Builds a cutover bundle from a source database executor.
    /// 
    /// IMPORTANT: This is a feature module utility. Callers must provide DatabaseExecutor.
    /// Only composition roots should create DatabaseActor directly.
    /// See ADR-0018 and td-317bbb.
    public static func buildBundle(source: any DatabaseExecutor) async throws -> PostgresCutoverBundle {
        let tableNames = try await discoverTableNames(source: source)
        let manifest = try await buildManifest(source: source, tableNames: tableNames)
        let script = try await buildPostgresScript(source: source, tables: manifest.tables)
        return PostgresCutoverBundle(manifest: manifest, postgresScript: script)
    }

    public static func buildManifest(
        source: any DatabaseExecutor,
        tableNames: [String]
    ) async throws -> PostgresCutoverManifest {
        var tables: [PostgresCutoverTable] = []
        var totalRows = 0

        for tableName in tableNames {
            let columns = try await inspectColumns(source: source, tableName: tableName)
            let rowCount = try await countRows(source: source, tableName: tableName)
            totalRows += rowCount
            tables.append(
                PostgresCutoverTable(
                    name: tableName,
                    rowCount: rowCount,
                    columns: columns
                )
            )
        }

        return PostgresCutoverManifest(
            sourcePath: source.path,
            generatedAt: Date(),
            totalRows: totalRows,
            tables: tables
        )
    }

    public static func buildPostgresScript(
        source: any DatabaseExecutor,
        tables: [PostgresCutoverTable]
    ) async throws -> String {
        var lines: [String] = [
            "-- Generated PostgreSQL cutover script",
            "-- Source: \(source.path)",
            "BEGIN;"
        ]

        for table in tables {
            lines.append("")
            lines.append("-- Table: \(table.name)")
            lines.append(table.createTableSQL)

            guard table.rowCount > 0 else { continue }

            let rows = try await fetchRows(source: source, tableName: table.name)
            let columnNames = table.columns.map(\.name)
            let insertPrefix = "INSERT INTO \(quoteIdentifier(table.name)) (\(columnNames.map { quoteIdentifier($0) }.joined(separator: ", "))) VALUES "

            for row in rows {
                let values = columnNames.map { columnName in
                    sqlLiteral(for: row[columnName] ?? .null)
                }
                lines.append(insertPrefix + "(\(values.joined(separator: ", ")));")
            }
        }

        lines.append("")
        lines.append("COMMIT;")
        return lines.joined(separator: "\n")
    }

    public static func exportManifest(
        sourcePath: String,
        outputURL: URL
    ) async throws {
        let source = DatabaseActor(path: sourcePath)
        try await source.open()
        defer { Task { await source.close() } }
        let bundle = try await buildBundle(source: source)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(bundle.manifest)
        try data.write(to: outputURL, options: [.atomic])
    }

    public static func exportScript(
        sourcePath: String,
        outputURL: URL
    ) async throws {
        let source = DatabaseActor(path: sourcePath)
        try await source.open()
        defer { Task { await source.close() } }
        let bundle = try await buildBundle(source: source)
        guard let data = bundle.postgresScript.data(using: .utf8) else { return }
        try data.write(to: outputURL, options: [.atomic])
    }

    private static func discoverTableNames(source: any DatabaseExecutor) async throws -> [String] {
        let rows = try await source.query(
            """
            SELECT table_name AS name
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_type = 'BASE TABLE'
            ORDER BY table_name ASC
            """
        )

        return rows.compactMap { $0.string(for: "name") }
    }

    private static func inspectColumns(
        source: any DatabaseExecutor,
        tableName: String
    ) async throws -> [PostgresCutoverColumn] {
        let rows = try await source.query(
            """
            SELECT
                column_name AS name,
                data_type AS type,
                is_nullable AS nullable,
                column_default AS dflt_value
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = \(quoteSQLLiteral(tableName))
            ORDER BY ordinal_position ASC
            """
        )
        let primaryKeyRows = try await source.query(
            """
            SELECT a.attname AS name
            FROM pg_index i
            JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
            JOIN pg_class c ON c.oid = i.indrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE i.indisprimary
              AND n.nspname = current_schema()
              AND c.relname = \(quoteSQLLiteral(tableName))
            """
        )
        let primaryKeyNames = Set(primaryKeyRows.compactMap { $0.string(for: "name") })

        return rows.compactMap { row in
            guard let name = row.string(for: "name") else { return nil }

            let sourceType = row.string(for: "type")
            let isPrimaryKey = primaryKeyNames.contains(name)
            let isNotNull = row.string(for: "nullable")?.uppercased() == "NO"
            let defaultValue = row.string(for: "dflt_value")

            return PostgresCutoverColumn(
                name: name,
                sourceType: sourceType,
                postgresType: postgresType(for: sourceType),
                isPrimaryKey: isPrimaryKey,
                isNotNull: isNotNull,
                defaultValue: defaultValue
            )
        }
    }

    private static func countRows(
        source: any DatabaseExecutor,
        tableName: String
    ) async throws -> Int {
        let rows = try await source.query("SELECT COUNT(*) AS count FROM \(quoteIdentifier(tableName));")
        return rows.first?.int(for: "count") ?? 0
    }

    private static func fetchRows(
        source: any DatabaseExecutor,
        tableName: String
    ) async throws -> [DatabaseRow] {
        try await source.query("SELECT * FROM \(quoteIdentifier(tableName)) ORDER BY 1 ASC;")
    }

    private static func postgresType(for sourceType: String?) -> String {
        let normalized = sourceType?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .uppercased() ?? ""

        if normalized.contains("INT") { return "BIGINT" }
        if normalized.contains("CHAR") || normalized.contains("CLOB") || normalized.contains("TEXT") { return "TEXT" }
        if normalized.contains("BLOB") { return "BYTEA" }
        if normalized.contains("REAL") || normalized.contains("FLOA") || normalized.contains("DOUB") { return "DOUBLE PRECISION" }
        if normalized.contains("BOOL") { return "BOOLEAN" }
        if normalized.contains("DATE") || normalized.contains("TIME") { return "TIMESTAMP" }
        return "TEXT"
    }

    private static func sqlLiteral(for value: DatabaseValue) -> String {
        switch value {
        case .text(let text):
            return "'\(text.replacingOccurrences(of: "'", with: "''"))'"
        case .int(let value):
            return "\(value)"
        case .double(let value):
            return value.isFinite ? "\(value)" : "NULL"
        case .blob(let data):
            let hex = data.map { String(format: "%02x", $0) }.joined()
            return "decode('\(hex)', 'hex')"
        case .date(let date):
            return "'\(ISO8601DateFormatter().string(from: date))'"
        case .null:
            return "NULL"
        }
    }

    private static func quoteIdentifier(_ identifier: String) -> String {
        "\"\(identifier.replacingOccurrences(of: "\"", with: "\"\""))\""
    }

    private static func quoteSQLLiteral(_ identifier: String) -> String {
        "'\(identifier.replacingOccurrences(of: "'", with: "''"))'"
    }
}
