// swift-tools-version: 5.10
// Package.swift
import PackageDescription
import Foundation

let isCI = ProcessInfo.processInfo.environment["CI"] != nil

let strictConcurrencySettings: [SwiftSetting] = [
    .unsafeFlags(["-strict-concurrency=targeted"])
]

let debugPerformanceSettings: [SwiftSetting] = [
    .unsafeFlags(["-Xfrontend", "-stats-output-dir", "-Xfrontend", ".build/stats"]),
    .unsafeFlags(["-Xfrontend", "-warn-long-function-bodies=100"]),
    .unsafeFlags(["-Xfrontend", "-warn-long-expression-type-checking=100"])
]

let skipTestsOnCI: [Target] = isCI ? [] : [] // Logic placeholder

let coreProducts: [Product] = [
    .library(name: "AnigmaFoundation", targets: ["AnigmaFoundation"]),
    .library(name: "AnigmaCore", targets: ["AnigmaCore"]),
    .library(name: "AnigmaPrimitives", targets: ["AnigmaPrimitives"]),
    .library(name: "CapsuleCore", targets: ["CapsuleCore"]),
    .library(name: "DatabaseCore", targets: ["DatabaseCore"]),
    .library(name: "ContractsCore", targets: ["ContractsCore"]),
    .library(name: "StorageCore", targets: ["StorageCore"]),
    .library(name: "CapabilityCore", targets: ["CapabilityCore"]),
    .library(name: "DoctrineCore", targets: ["DoctrineCore"]),
    .library(name: "SecurityEventsManager", targets: ["SecurityEventsManager"]),
    .library(name: "TelemetryCore", targets: ["TelemetryCore"]),
    .library(name: "ExecutionCore", targets: ["ExecutionCore"]),
    .library(name: "InferenceCore", targets: ["InferenceCore"]),
    .library(name: "CanonicalTokenizer", targets: ["CanonicalTokenizer"]),
    .library(name: "AnigmaASTServicesCore", type: .dynamic, targets: ["AnigmaASTServicesCore"]),
    .library(name: "PlatformCore", targets: ["PlatformCore"]),
    .library(name: "AnigmaClientKit", targets: ["AnigmaClientKit"]),
    .library(name: "AnigmaHostKit", targets: ["AnigmaHostKit"]),
    .library(name: "AnigmaHostMac", targets: ["AnigmaHostMac"]),
    .library(name: "AnigmaSidecar", targets: ["AnigmaSidecar"]),
    .library(name: "AnigmaSystemSpine", targets: ["AnigmaSystemSpine"]),
    .library(name: "DataCore", targets: ["DataCore"]),
    .library(name: "DataEngine", targets: ["DataEngine"]),
    .library(name: "RendererKit", targets: ["RendererKit"]),
    .library(name: "DataUI", targets: ["DataUI"]),
    .library(name: "AnigmaTUI", targets: ["AnigmaTUI"]),
    .library(name: "Workflows", targets: ["Workflows"]),
    .library(name: "ExportCore", targets: ["ExportCore"]),
    .library(name: "ExportUI", targets: ["ExportUI"]),
    .library(name: "AnigmaWork", targets: ["AnigmaWork"]),
    .library(name: "AnigmaCorporate", targets: ["AnigmaCorporate"]),
    .library(name: "AnigmaEducation", targets: ["AnigmaEducation"]),
    
    // Native Capability Modules
    .library(name: "DocumentIRKit", targets: ["DocumentIRKit"]),
    .library(name: "ContainerKit", targets: ["ContainerKit"]),
    .library(name: "OOXMLKit", targets: ["OOXMLKit"]),
    .library(name: "DocumentRenderKit", targets: ["DocumentRenderKit"]),
    .library(name: "TypographyKit", targets: ["TypographyKit"]),
    .library(name: "ColorKit", targets: ["ColorKit"]),
    .library(name: "VectorOpsKit", targets: ["VectorOpsKit"]),
    .library(name: "CompressionKit", targets: ["CompressionKit"]),
    .library(name: "TextChunkingCapsule", targets: ["TextChunkingCapsule"]),
    .library(name: "VizAggregationCapsule", targets: ["VizAggregationCapsule"]),
    .library(name: "MediaFingerprintCapsule", targets: ["MediaFingerprintCapsule"]),
    .library(name: "VectorCapsule", targets: ["VectorCapsule"]),
    .library(name: "TextPipelineCapsule", targets: ["TextPipelineCapsule"]),
    .library(name: "VectorIndexCapsule", targets: ["VectorIndexCapsule"]),
    .library(name: "CosineSimilarityCapsule", targets: ["CosineSimilarityCapsule"]),
    .library(name: "RankFusionCapsule", targets: ["RankFusionCapsule"]),
    .library(name: "AnimationKit", targets: ["AnimationKit"]),
    .library(name: "SceneGraphCapsule", targets: ["SceneGraphCapsule"]),
    .library(name: "RenderPlanCapsule", targets: ["RenderPlanCapsule"]),
    .library(name: "HitTestCapsule", targets: ["HitTestCapsule"]),
    .library(name: "ObservabilityKit", targets: ["ObservabilityKit"]),
    .library(name: "SidecarOfficeService", targets: ["SidecarOfficeService"]),
    .library(name: "SidecarPDFService", targets: ["SidecarPDFService"]),
    .library(name: "SidecarTranslateService", targets: ["SidecarTranslateService"]),
    .library(name: "AnigmaNativeShims", targets: ["AnigmaNativeShims"]),
    
    // Canvas Engine Modules
    .library(name: "RuntimeOrchestrator", targets: ["RuntimeOrchestrator"]),
    .library(name: "PlatformAdapters", targets: ["PlatformAdapters"]),
    .library(name: "AnigmaUI", targets: ["AnigmaUI"]),
]

let executableProducts: [Product] = [
    .executable(name: "harmonia-surface", targets: ["HarmoniaSurface"]),
    .executable(name: "doctrine", targets: ["DoctrineCLI"]),
    .executable(name: "outlineum-zine", targets: ["OutlineumZine"]),
    .executable(name: "diaplasion-pipeline", targets: ["DiaplasionPipeline"]),
    .executable(name: "accessum-flow", targets: ["AccessumFlow"]),
    .executable(name: "ml-worker", targets: ["MLWorkerExecutable"]),
    .executable(name: "anigma-ast-services", targets: ["anigma-ast-services"]),
    .executable(name: "anigma", targets: ["AnigmaCLIExecutable"]),
    .executable(name: "anigma-cli", targets: ["AnigmaCLIExecutable"]),
    .executable(name: "anigma-app", targets: ["AnigmaAppMacExecutable"]),
    .executable(name: "anigma-mcp", targets: ["AnigmaMCPExecutable"]),
    .executable(name: "anigma-gemini-bridge", targets: ["AnigmaGeminiBridge"]),
    .executable(name: "anigma-status-bar", targets: ["AnigmaStatusBar"])
]

let capabilityProducts: [Product] = [
    .library(name: "HarmoniaModule", targets: ["HarmoniaModule"]),
    .library(name: "DiaplasionModule", targets: ["DiaplasionModule"]),
    .library(name: "AccessumModule", targets: ["AccessumModule"]),
    .library(name: "OutlineumModule", targets: ["OutlineumModule"]),
    .library(name: "PragmaModule", targets: ["PragmaModule"]),
    .library(name: "ConexusModule", targets: ["ConexusModule"]),
    .library(name: "CodexModule", targets: ["CodexModule"]),
    .library(name: "TranscriptumModule", targets: ["TranscriptumModule"]),
    .library(name: "ObservatoriumModule", targets: ["ObservatoriumModule"]),
    .library(name: "PolytroposModule", targets: ["PolytroposModule"]),
    .library(name: "VectorumModule", targets: ["VectorumModule"]),
    .library(name: "PraxisCore", targets: ["PraxisCore"]),
    .library(name: "CathedralModule", targets: ["CathedralModule"]),
    .library(name: "ContextumModule", targets: ["ContextumModule"]),
    .library(name: "ArtifactStoreModule", targets: ["ArtifactStoreModule"]),
    .library(name: "DevelopumModule", targets: ["DevelopumModule"]),
    .library(name: "ModelRegistryModule", targets: ["ModelRegistryModule"]),
    .library(name: "AnigmaAgents", targets: ["AnigmaAgents"]),
    .library(name: "AnigmaAIConsole", targets: ["AnigmaAIConsole"]),
    .executable(name: "harmonia", targets: ["HarmoniaCLI"]),
    .executable(name: "anigmad", targets: ["AnigmaDaemon"]),
    .library(name: "AnigmaMCPModule", targets: ["AnigmaMCPModule"])
]

let package = Package(
    name: "Anigma",
    platforms: [
        .macOS(.v14), .iOS(.v17), .tvOS(.v17), .watchOS(.v10)
    ],
    products: coreProducts + executableProducts + capabilityProducts,
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.3.0"),
        .package(path: "Tools/Vendor/swift-syntax"),
        .package(url: "https://github.com/ml-explore/mlx-swift.git", from: "0.29.1"),
        .package(url: "https://github.com/ml-explore/mlx-swift-lm.git", from: "2.29.2"),
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "6.0.0"),
        .package(url: "https://github.com/nixberg/blake3-swift.git", from: "0.1.2"),
        .package(url: "https://github.com/grpc/grpc-swift.git", from: "2.0.0"),
        .package(url: "https://github.com/apple/swift-numerics.git", from: "1.0.2"),
        .package(url: "https://github.com/jdfergason/swift-toml.git", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-crypto.git", from: "3.0.0"),
        .package(url: "https://github.com/tree-sitter/swift-tree-sitter.git", from: "0.8.0"),
        .package(url: "https://github.com/apple/swift-cmark.git", from: "0.5.0"),
        .package(url: "https://github.com/hummingbird-project/hummingbird.git", from: "2.0.0"),
        .package(url: "https://github.com/swift-server/async-http-client.git", from: "1.19.0"),
        .package(url: "https://github.com/modelcontextprotocol/swift-sdk.git", from: "0.4.1"),
    ],
    targets: [
        .target(name: "CHarfBuzz", path: "Packages/CHarfBuzz", publicHeadersPath: "."),
        .target(name: "CFreeType", path: "Packages/CFreeType", publicHeadersPath: "."),
        .target(
            name: "CClipper2",
            path: "Packages/CClipper2",
            exclude: ["example.c", "Package.swift"],
            sources: [
                "clipper2_wrapper.cpp",
                "Clipper2/CPP/Clipper2Lib/src/clipper.engine.cpp",
                "Clipper2/CPP/Clipper2Lib/src/clipper.offset.cpp",
                "Clipper2/CPP/Clipper2Lib/src/clipper.triangulation.cpp",
                "Clipper2/CPP/Clipper2Lib/src/clipper.rectclip.cpp",
                "Clipper2/CPP/Utils/clipper.svg.cpp",
            ],
            publicHeadersPath: ".",
            cxxSettings: [
                .headerSearchPath("Clipper2/CPP/Clipper2Lib/include"),
                .headerSearchPath("Clipper2/CPP/Utils"),
                .unsafeFlags(["-Wno-sign-conversion", "-Wno-float-conversion", "-Wno-unused-parameter"]),
            ]
        ),
        .target(name: "CPDFium", path: "Packages/CPDFium", publicHeadersPath: ".", linkerSettings: [.linkedLibrary("pdfium"), .unsafeFlags(["-L", "../../Vendor/lib"])]),
        .target(
            name: "CSQLiteVec",
            path: "Packages/CSQLiteVec",
            publicHeadersPath: ".",
            cSettings: [
                .define("SQLITE_CORE"),
                .define("SQLITE_VEC_VERSION", to: "\"0.1.7-alpha.2\""),
                .define("SQLITE_VEC_VERSION_MAJOR", to: "0"),
                .define("SQLITE_VEC_VERSION_MINOR", to: "1"),
                .define("SQLITE_VEC_VERSION_PATCH", to: "7"),
                .define("SQLITE_VEC_DATE", to: "\"2024-01-10\""),
                .define("SQLITE_VEC_SOURCE", to: "\"anigma-cli\""),
                .define("SQLITE_VEC_API", to: ""),
                .define("SQLITE_VEC_ENABLE_NEON", .when(platforms: [.macOS, .iOS, .tvOS, .watchOS])),
                .unsafeFlags(["-Wno-c23-extensions"]),
            ]
        ),
        .target(
            name: "KernelNative",
            path: "Native/Shims/src/kernel",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("../../include")]
        ),
        .target(
            name: "AnigmaNativeShims",
            dependencies: ["CClipper2", "CPDFium", "KernelNative"],
            path: "Native/Shims",
            exclude: ["Package.swift"],
            sources: ["src/kernel_abi.c"],
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("../../Vendor/include"),
            ],
            swiftSettings: strictConcurrencySettings
        ),
        .target(
            name: "NativeKernel",
            dependencies: ["AnigmaNativeShims"],
            path: "Native/Kernel",
            sources: ["src/kernel_context.cpp"],
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .headerSearchPath("../Shims/include"),
                .unsafeFlags(["-O3", "-ffast-math"]) // Performance optimizations
            ]
        ),
        .target(name: "AnigmaFoundation", path: "Packages/AnigmaFoundation", swiftSettings: strictConcurrencySettings + debugPerformanceSettings),
        .target(name: "AnigmaCore",
             dependencies: ["AnigmaFoundation", "AnigmaPrimitives", "ContractsCore", "DatabaseCore", "StorageCore", "InferenceCore", "GovernanceCore", "SecurityEventsManager", "TextChunkingCapsule", "LayoutEngineCapsule", .product(name: "Toml", package: "swift-toml"), .product(name: "Crypto", package: "swift-crypto"), .product(name: "BLAKE3", package: "blake3-swift")], path: "Packages/AnigmaCore", swiftSettings: strictConcurrencySettings),

        .target(name: "AnigmaPrimitives", dependencies: [.product(name: "BLAKE3", package: "blake3-swift")], path: "Packages/AnigmaPrimitives", swiftSettings: strictConcurrencySettings),
        .target(name: "DatabaseCore", dependencies: ["ContractsCore", .product(name: "GRDB", package: "GRDB.swift")], path: "Packages/DatabaseCore", swiftSettings: strictConcurrencySettings),
        .target(name: "ContractsCore", dependencies: ["AnigmaPrimitives", .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "Packages/ContractsCore", swiftSettings: strictConcurrencySettings),
        .target(name: "ModelRegistry", dependencies: ["ContractsCore"], path: "Packages/ModelRegistry/Sources", swiftSettings: strictConcurrencySettings),
        .target(name: "CapabilityCore", dependencies: ["AnigmaPrimitives", "AnigmaCore"], path: "Packages/CapabilityCore", swiftSettings: strictConcurrencySettings),
        .target(name: "DoctrineCore", dependencies: [], path: "Packages/DoctrineCore", swiftSettings: strictConcurrencySettings),
        .target(name: "TelemetryCore", dependencies: ["AnigmaPrimitives"], path: "Packages/TelemetryCore", swiftSettings: strictConcurrencySettings),
        .target(name: "ExecutionCore", dependencies: ["TelemetryCore", "AnigmaPrimitives", .product(name: "BLAKE3", package: "blake3-swift")], path: "Packages/ExecutionCore", swiftSettings: strictConcurrencySettings),
        .target(name: "InferenceCore", dependencies: [], path: "Packages/InferenceCore", swiftSettings: strictConcurrencySettings),
        .target(name: "CanonicalTokenizer", dependencies: ["ContractsCore", .product(name: "Crypto", package: "swift-crypto"), .product(name: "Numerics", package: "swift-numerics")], path: "Packages/CanonicalTokenizer", swiftSettings: strictConcurrencySettings),
        .target(name: "GovernanceCore", dependencies: ["AnigmaPrimitives", "DatabaseCore", "ContractsCore", .product(name: "Toml", package: "swift-toml")], path: "Packages/GovernanceCore", swiftSettings: strictConcurrencySettings),
        .target(name: "StorageCore", dependencies: ["DatabaseCore", "GovernanceCore"], path: "Packages/StorageCore", swiftSettings: strictConcurrencySettings),
        .target(name: "GovernedMigrationCore", dependencies: ["DoctrineCore", "SecurityEventsManager", "DatabaseCore"], path: "Packages/GovernedMigrationCore", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaASTServicesCore", dependencies: ["AnigmaPrimitives", .product(name: "SwiftSyntax", package: "swift-syntax"), .product(name: "SwiftParser", package: "swift-syntax")], path: "Packages/AnigmaASTServices", exclude: ["main.swift"], swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "anigma-ast-services", dependencies: ["AnigmaASTServicesCore", .product(name: "SwiftSyntax", package: "swift-syntax"), .product(name: "SwiftParser", package: "swift-syntax"), .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "Packages/AnigmaASTServicesCLI", swiftSettings: strictConcurrencySettings),
        .target(name: "SecurityEventsManager", dependencies: [], path: "Packages/SecurityEventsManager", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaClientKit", dependencies: ["ContractsCore"], path: "Packages/AnigmaClientKit", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaSidecar", dependencies: ["AnigmaPrimitives", .product(name: "AsyncHTTPClient", package: "async-http-client")], path: "Packages/AnigmaSidecar", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaSystemSpine", dependencies: [], path: "Packages/AnigmaSystemSpine", swiftSettings: strictConcurrencySettings),
        .target(name: "DataCore", dependencies: ["AnigmaPrimitives"], path: "Packages/DataCore", swiftSettings: strictConcurrencySettings),
        .target(name: "DataEngine", dependencies: ["DataCore", "AnigmaPrimitives", "AnigmaSystemSpine"], path: "Packages/DataEngine", swiftSettings: strictConcurrencySettings),
        .target(name: "RendererKit", dependencies: ["DataCore"], path: "Packages/RendererKit", swiftSettings: strictConcurrencySettings),
        .target(name: "DataUI", dependencies: ["DataCore", "DataEngine", "RendererKit", "AnigmaClientKit"], path: "Packages/DataUI", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaTUI", dependencies: [], path: "Packages/AnigmaTUI/Sources/AnigmaTUI", swiftSettings: strictConcurrencySettings),
        .target(name: "Workflows", dependencies: ["DataCore", "DataEngine", "AnigmaSystemSpine"], path: "Packages/Workflows", swiftSettings: strictConcurrencySettings),
        .target(name: "ExportCore", dependencies: ["AnigmaSystemSpine", "DataCore"], path: "Packages/ExportCore", swiftSettings: strictConcurrencySettings),
        .target(name: "ExportUI", dependencies: ["ExportCore", "AnigmaSystemSpine", "DataCore"], path: "Packages/ExportUI", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaWork", dependencies: ["AnigmaCore", "DataCore", "DataEngine", "AnigmaSystemSpine", "ExportCore", "RendererKit"], path: "Packages/AnigmaWork", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCorporate", dependencies: ["AnigmaCore", "HarmoniaModule", "AnigmaSystemSpine"], path: "Packages/AnigmaCorporate", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaEducation", dependencies: ["AnigmaCore", "AnigmaSystemSpine"], path: "Packages/AnigmaEducation", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaAgents", dependencies: ["AnigmaCore", "AnigmaSystemSpine", "DataCore", "DataEngine", "AnigmaCorporate", "AnigmaEducation", "HarmoniaModule", "PraxisCore"], path: "Packages/AnigmaAgents", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaAIConsole", dependencies: ["AnigmaCore", "AnigmaSystemSpine", "AnigmaAgents", "DataCore"], path: "Packages/AnigmaAIConsole", swiftSettings: strictConcurrencySettings),
        .target(name: "DocumentIRKit", dependencies: [], path: "Packages/DocumentIRKit", swiftSettings: strictConcurrencySettings),
        .target(name: "ContainerKit", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives"], path: "Packages/ContainerKit", swiftSettings: strictConcurrencySettings),
        .target(name: "OOXMLKit", dependencies: ["ContainerKit", "AnigmaNativeShims", "AnigmaPrimitives"], path: "Packages/OOXMLKit", swiftSettings: strictConcurrencySettings),
        .target(name: "DocumentRenderKit", dependencies: ["DataCore", "AnigmaNativeShims", "AnigmaPrimitives"], path: "Packages/DocumentRenderKit", swiftSettings: strictConcurrencySettings),
        .target(name: "TypographyKit", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives"], path: "Packages/TypographyKit", swiftSettings: strictConcurrencySettings),
        .target(name: "ColorKit", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives"], path: "Packages/ColorKit", swiftSettings: strictConcurrencySettings),
        .target(name: "VectorOpsKit", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore"], path: "Packages/VectorOpsKit", swiftSettings: strictConcurrencySettings),
        .target(name: "CapsuleCore", dependencies: ["AnigmaPrimitives", "AnigmaNativeShims"], path: "Packages/CapsuleCore/Sources/CapsuleCore", swiftSettings: strictConcurrencySettings),
        .target(
            name: "CompressionNative",
            path: "Packages/CompressionKit/Sources/CompressionNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "CompressionKit", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "CompressionNative"], path: "Packages/CompressionKit", exclude: ["Sources/CompressionNative"], swiftSettings: strictConcurrencySettings),
        .target(
            name: "TextChunkingNative",
            path: "Packages/TextChunkingCapsule/Sources/TextChunkingNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "TextChunkingCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "TextChunkingNative"], path: "Packages/TextChunkingCapsule", exclude: ["Sources/TextChunkingNative"], swiftSettings: strictConcurrencySettings),
        .target(
            name: "LayoutEngineNative",
            path: "Packages/LayoutEngineCapsule/Sources/LayoutEngineNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "LayoutEngineCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "LayoutEngineNative"], path: "Packages/LayoutEngineCapsule", exclude: ["Sources/LayoutEngineNative"], swiftSettings: strictConcurrencySettings),
        .target(
            name: "VizAggregationNative",
            path: "Packages/VizAggregationCapsule/Sources/VizAggregationNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "VizAggregationCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "VizAggregationNative"], path: "Packages/VizAggregationCapsule", exclude: ["Sources/VizAggregationNative"], swiftSettings: strictConcurrencySettings),
        .target(
            name: "MediaFingerprintNative",
            path: "Packages/MediaFingerprintCapsule/Sources/MediaFingerprintNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "MediaFingerprintCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "MediaFingerprintNative"], path: "Packages/MediaFingerprintCapsule", exclude: ["Sources/MediaFingerprintNative"], swiftSettings: strictConcurrencySettings),
        .target(
            name: "MediaContainerNative",
            path: "Packages/MediaContainerCapsule/Sources/MediaContainerNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "MediaContainerCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "MediaContainerNative"], path: "Packages/MediaContainerCapsule", exclude: ["Sources/MediaContainerNative"], swiftSettings: strictConcurrencySettings),
        .target(
            name: "VectorNative",
            path: "Packages/VectorCapsule/Sources/VectorNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "VectorCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "VectorNative"], path: "Packages/VectorCapsule", exclude: ["Sources/VectorNative"], swiftSettings: strictConcurrencySettings + [.unsafeFlags(["-whole-module-optimization"])]),
        .target(
            name: "TextPipelineNative",
            path: "Packages/TextPipelineCapsule/Sources/TextPipelineNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "TextPipelineCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "TextPipelineNative"], path: "Packages/TextPipelineCapsule", exclude: ["Sources/TextPipelineNative"], swiftSettings: strictConcurrencySettings + [.unsafeFlags(["-whole-module-optimization"])]),
        .target(
            name: "VectorIndexNative",
            path: "Packages/VectorIndexCapsule/Sources/VectorIndexNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "VectorIndexCapsule", dependencies: ["AnigmaPrimitives", "CapsuleCore", "VectorIndexNative"], path: "Packages/VectorIndexCapsule", exclude: ["Sources/VectorIndexNative"], swiftSettings: strictConcurrencySettings + [.unsafeFlags(["-whole-module-optimization"])]),
        .target(
            name: "CosineNative",
            path: "Packages/CosineSimilarityCapsule/Sources/CosineNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "CosineSimilarityCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "CosineNative"], path: "Packages/CosineSimilarityCapsule", exclude: ["Sources/CosineNative"], swiftSettings: strictConcurrencySettings + [.unsafeFlags(["-whole-module-optimization"])]),
        .target(
            name: "RankFusionNative",
            path: "Packages/RankFusionCapsule/Sources/RankFusionNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "RankFusionCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "RankFusionNative"], path: "Packages/RankFusionCapsule", exclude: ["Sources/RankFusionNative"], swiftSettings: strictConcurrencySettings + [.unsafeFlags(["-whole-module-optimization"])]),
        .target(
            name: "SceneGraphNative",
            path: "Packages/SceneGraphCapsule/Sources/SceneGraphNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "SceneGraphCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "SceneGraphNative"], path: "Packages/SceneGraphCapsule", exclude: ["Sources/SceneGraphNative"], swiftSettings: strictConcurrencySettings),
        .target(
            name: "RenderPlanNative",
            path: "Packages/RenderPlanCapsule/Sources/RenderPlanNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "RenderPlanCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "SceneGraphCapsule", "RenderPlanNative"], path: "Packages/RenderPlanCapsule", exclude: ["Sources/RenderPlanNative"], swiftSettings: strictConcurrencySettings),
        .target(
            name: "HitTestNative",
            path: "Packages/HitTestCapsule/Sources/HitTestNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "HitTestCapsule", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "CapsuleCore", "SceneGraphCapsule", "HitTestNative"], path: "Packages/HitTestCapsule", exclude: ["Sources/HitTestNative"], swiftSettings: strictConcurrencySettings),
        .target(
            name: "AnimationNative",
            path: "Packages/AnimationKit/Sources/AnimationNative",
            publicHeadersPath: "include",
            cxxSettings: [.headerSearchPath("include")]
        ),
        .target(name: "AnimationKit", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives", "AnimationNative"], path: "Packages/AnimationKit", exclude: ["Sources/AnimationNative"], swiftSettings: strictConcurrencySettings),
        .target(name: "ObservabilityKit", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives"], path: "Packages/ObservabilityKit", swiftSettings: strictConcurrencySettings),
        .target(name: "SidecarOfficeService", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives"], path: "Packages/SidecarOfficeService", swiftSettings: strictConcurrencySettings),
        .target(name: "SidecarPDFService", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives"], path: "Packages/SidecarPDFService", swiftSettings: strictConcurrencySettings),
        .target(name: "SidecarTranslateService", dependencies: ["AnigmaNativeShims", "AnigmaPrimitives"], path: "Packages/SidecarTranslateService", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaHostKit", dependencies: ["AnigmaClientKit", "AnigmaCore", "AnigmaPrimitives", "ContractsCore", "AnigmaDaemonCore", "AnigmaSidecar"], path: "Packages/AnigmaHostKit", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaHostMac", dependencies: ["AnigmaClientKit", "AnigmaHostKit", "ContractsCore", "AnigmaSidecar", .product(name: "GRDB", package: "GRDB.swift"), .product(name: "Crypto", package: "swift-crypto"), .product(name: "BLAKE3", package: "blake3-swift"), .product(name: "SwiftTreeSitter", package: "swift-tree-sitter"), .product(name: "cmark-gfm", package: "swift-cmark")], path: "Packages/AnigmaHostMac", swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "HarmoniaSurface", dependencies: ["AnigmaCore", "MLWorkerCommon", .product(name: "MLXLMCommon", package: "mlx-swift-lm"), .product(name: "MLXEmbedders", package: "mlx-swift-lm"), .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "Packages/HarmoniaSurface", swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "DoctrineCLI", dependencies: ["HarmoniaModule", .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "Packages/DoctrineCLI", swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "OutlineumZine", dependencies: ["AnigmaCore", "OutlineumModule", .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "Packages/OutlineumZine", swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "DiaplasionPipeline", dependencies: ["AnigmaCore", "DiaplasionModule", "ContractsCore", .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "Packages/DiaplasionPipeline", swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "AccessumFlow", dependencies: ["AnigmaCore", "DatabaseCore", "DiaplasionModule", "OutlineumModule", "HarmoniaModule", "MLWorkerCommon", .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "Packages/AccessumFlow", swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "MLWorkerExecutable", dependencies: ["MLWorkerCommon", "ContractsCore", "AnigmaCore", "AnigmaPrimitives", .product(name: "MLXLMCommon", package: "mlx-swift-lm"), .product(name: "MLXEmbedders", package: "mlx-swift-lm"), .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "Packages/MLWorkerExecutable", swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "AnigmaAppMacExecutable", dependencies: ["AnigmaClientKit", "AnigmaHostMac", "AnigmaSystemSpine", "HarmoniaModule", "OutlineumModule", "DataUI", "AnigmaAgents", "AnigmaAIConsole", "ExportCore", "ExportUI", "AnigmaWork", "DataEngine", "ContractsCore", "ContextumModule", "AnigmaMCPModule", "DevelopumModule"], path: "Sources/AnigmaAppMac", swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "AnigmaGeminiBridge", dependencies: ["AnigmaCore", "AnigmaPrimitives", .product(name: "Hummingbird", package: "hummingbird")], path: "Packages/AnigmaGeminiBridge/Sources/AnigmaGeminiBridge", swiftSettings: strictConcurrencySettings),
        .target(name: "HarmoniaModule", dependencies: ["AnigmaCore", "AnigmaPrimitives", "CapabilityCore", "DatabaseCore", "TelemetryCore", "ExecutionCore", "DoctrineCore", "SecurityEventsManager", "AnigmaASTServicesCore", "MLWorkerCommon", .product(name: "MLXEmbedders", package: "mlx-swift-lm"), "CathedralModule", "StorageCore", "GovernedMigrationCore", "AnigmaCLIProviders", "AnigmaCLIRouter", "AnigmaCLIOrchestrator", "AnigmaCLIEventing", "AnigmaCLIGovernance", .product(name: "GRDB", package: "GRDB.swift"), .product(name: "BLAKE3", package: "blake3-swift")], path: "Packages/HarmoniaModule", swiftSettings: strictConcurrencySettings),
        .target(name: "HarmoniaMemory", dependencies: ["AnigmaCore", "TelemetryCore", .product(name: "GRDB", package: "GRDB.swift")], path: "Packages/HarmoniaMemory", swiftSettings: strictConcurrencySettings),
        .target(name: "DiaplasionModule", dependencies: ["AnigmaCore", "TextChunkingCapsule"], path: "Packages/DiaplasionModule", swiftSettings: strictConcurrencySettings),
        .target(name: "AccessumModule", dependencies: ["AnigmaCore", "ContractsCore", "TelemetryCore"], path: "Packages/AccessumModule", swiftSettings: strictConcurrencySettings),
        .target(name: "OutlineumModule", dependencies: ["AnigmaCore"], path: "Packages/OutlineumModule", swiftSettings: strictConcurrencySettings),
        .target(name: "PragmaModule", dependencies: ["AnigmaCore", "AnigmaPrimitives", "ContractsCore"], path: "Packages/PragmaModule", swiftSettings: strictConcurrencySettings),
        .target(name: "ConexusModule", dependencies: ["AnigmaCore"], path: "Packages/ConexusModule", swiftSettings: strictConcurrencySettings),
        .target(name: "CodexModule", dependencies: ["AnigmaCore"], path: "Packages/CodexModule", swiftSettings: strictConcurrencySettings),
        .target(name: "TranscriptumModule", dependencies: ["AnigmaCore"], path: "Packages/TranscriptumModule", swiftSettings: strictConcurrencySettings),
        .target(name: "ObservatoriumModule", dependencies: ["AnigmaCore", "TelemetryCore"], path: "Packages/ObservatoriumModule", swiftSettings: strictConcurrencySettings),
        .target(name: "PolytroposModule", dependencies: ["AnigmaCore", "AnigmaPrimitives", "MediaContainerCapsule"], path: "Packages/PolytroposModule", swiftSettings: strictConcurrencySettings),
        .target(name: "VectorumModule", dependencies: ["ContractsCore", "AnigmaCore", "CapabilityCore"], path: "Packages/VectorumModule", swiftSettings: strictConcurrencySettings),
        .target(name: "PraxisCore", dependencies: [], path: "Packages/PraxisCore", swiftSettings: strictConcurrencySettings),
        .target(name: "CathedralModule", dependencies: ["AnigmaCore", "DatabaseCore", "ContextumModule"], path: "Packages/CathedralModule", swiftSettings: strictConcurrencySettings),
        .target(name: "ContextumModule", dependencies: ["AnigmaCore", "DatabaseCore", "ContractsCore", "CapsuleCore", "TextChunkingCapsule", "CompressionKit", "VizAggregationCapsule"], path: "Sources/ContextumModule", swiftSettings: strictConcurrencySettings),
        .target(name: "ArtifactStoreModule", dependencies: ["AnigmaCore", "ContractsCore", "DatabaseCore"], path: "Sources/ArtifactStoreModule", swiftSettings: strictConcurrencySettings),
        .target(name: "DevelopumModule", dependencies: ["AnigmaCore", "DatabaseCore", "ContractsCore", "TelemetryCore", "ExecutionCore", "TextChunkingCapsule", "AnigmaSidecar", .product(name: "GRDB", package: "GRDB.swift"), .product(name: "BLAKE3", package: "blake3-swift")], path: "Packages/DevelopumModule", swiftSettings: strictConcurrencySettings),
        .target(name: "ModelRegistryModule", dependencies: ["AnigmaCore", "ContractsCore", "DatabaseCore"], path: "Sources/ModelRegistryModule", swiftSettings: strictConcurrencySettings),
        .target(name: "PraxisModule", dependencies: ["PraxisCore", "ContractsCore"], path: "Packages/PraxisModule", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLICore", dependencies: ["ContractsCore", "AnigmaCore"], path: "Packages/AnigmaCLI/Core", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIEventing", dependencies: ["AnigmaCLICore"], path: "Packages/AnigmaCLI/Eventing", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIProviders", dependencies: ["AnigmaCLICore", "AnigmaCLIDatabase", "ContractsCore"], path: "Packages/AnigmaCLI/Providers", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIRouter", dependencies: ["AnigmaCLICore", "AnigmaCLIProviders"], path: "Packages/AnigmaCLI/Router", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIGovernance", dependencies: ["AnigmaCLICore", "AnigmaCLIProviders"], path: "Packages/AnigmaCLI/Governance", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIOrchestrator", dependencies: ["AnigmaCLICore", "AnigmaCLIEventing", "AnigmaCLIGovernance", "AnigmaCLIProviders", "AnigmaCLIRouter"], path: "Packages/AnigmaCLI/Orchestrator", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIOnboarding", dependencies: ["AnigmaCLICore", "AnigmaCLIDatabase", "AnigmaCLIProviders", "AnigmaCLIML", "DatabaseCore", "ModelManagement", .product(name: "GRDB", package: "GRDB.swift")], path: "Packages/AnigmaCLI/Onboarding", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIDatabase", dependencies: ["CSQLiteVec", "AnigmaCLICore", "TextChunkingCapsule", .product(name: "Crypto", package: "swift-crypto")], path: "Packages/AnigmaCLI/Database", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIRAG", dependencies: ["CSQLiteVec", "TextChunkingCapsule"], path: "Packages/AnigmaCLI/RAG", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIML", dependencies: ["AnigmaCLICore", "AnigmaCLIDatabase", "AnigmaCLIMLIntegration", "AnigmaCLIProviders", "AnigmaCLILocalInference", "AnigmaCLIRAG"], path: "Packages/AnigmaCLI/ML", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIUI", dependencies: [], path: "Packages/AnigmaCLI/UI", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLITUI", dependencies: ["AnigmaCLICore", "AnigmaCLIEventing", "AnigmaCLIDatabase", "AnigmaCLIML", "HarmoniaModule", "AnigmaTUI", "AnigmaSidecar"], path: "Packages/AnigmaCLI/Sources/TUI", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIMLIntegration", dependencies: [], path: "Packages/AnigmaCLI/MLIntegration", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLIMCP", dependencies: ["AnigmaCLICore", "AnigmaPrimitives", "ContractsCore"], path: "Packages/AnigmaCLIMCP", swiftSettings: strictConcurrencySettings),
        .target(name: "RLMModule", dependencies: ["AnigmaCore", "AnigmaPrimitives", "DatabaseCore", "ContextumModule", "ArtifactStoreModule", "HarmoniaModule", "VectorIndexCapsule", "TextPipelineCapsule", "TextChunkingCapsule", "LayoutEngineCapsule", "CapsuleCore", "InferenceCore"], path: "Sources/RLMModule", swiftSettings: strictConcurrencySettings),
        .target(name: "ModelManagement", dependencies: [.product(name: "Crypto", package: "swift-crypto")], path: "Packages/AnigmaCLI/Sources/ModelManagement", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaCLILocalInference", dependencies: [.product(name: "MLX", package: "mlx-swift"), .product(name: "MLXNN", package: "mlx-swift"), .product(name: "MLXRandom", package: "mlx-swift"), .product(name: "MLXOptimizers", package: "mlx-swift")], path: "Packages/AnigmaCLI/Sources/LocalInference", swiftSettings: strictConcurrencySettings),
        .executableTarget(name: "HarmoniaCLI", dependencies: ["AnigmaCLICore", "AnigmaCLIEventing", "AnigmaCLIGovernance", "AnigmaCLIOrchestrator", "AnigmaCLIProviders", "AnigmaCLIRouter", "AnigmaCore", "ContractsCore", "HarmoniaModule", "PraxisModule", "PraxisCore", "MLWorkerCommon", "HarmoniaMemory", "TechDebtAudit", "ExecutionCore", "StorageCore", "AnigmaDaemonCore", .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "Packages/HarmoniaCLI", swiftSettings: strictConcurrencySettings),
        .executableTarget(
            name: "AnigmaCLIExecutable",
            dependencies: [
                "AnigmaCLICore",
                "AnigmaCLIEventing",
                "AnigmaCLIOrchestrator",
                "AnigmaCLIProviders",
                "AnigmaCLIMCP",
                "AnigmaCLIRouter",
                "AnigmaCLIGovernance",
                "AnigmaCLIOnboarding",
                "AnigmaCLIUI",
                "AnigmaCLITUI",
                "ModelManagement",
                "AnigmaCore",
                "AnigmaPrimitives",
                "ContractsCore",
                "AnigmaMCPModule",
                "ModelRegistry",
                "HarmoniaModule",
                "AnigmaSidecar",
                .product(name: "MCP", package: "swift-sdk"),
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
                .product(name: "GRDB", package: "GRDB.swift"),
                .product(name: "BLAKE3", package: "blake3-swift")
            ],
            path: "Packages/AnigmaCLI/Executable",
            swiftSettings: strictConcurrencySettings
        ),
        .executableTarget(
            name: "AnigmaStatusBar",
            dependencies: [
                "AnigmaSidecar",
                "AnigmaPrimitives"
            ],
            path: "Packages/AnigmaStatusBar",
            swiftSettings: strictConcurrencySettings
        ),
        .executableTarget(name: "AnigmaDaemon", dependencies: ["AnigmaDaemonCore", "AnigmaSidecar", "StorageCore", "HarmoniaModule", "SidecarOfficeService", "SidecarPDFService", "SidecarTranslateService"], path: "Packages/AnigmaDaemon", swiftSettings: strictConcurrencySettings),
        .target(name: "AnigmaDaemonCore", dependencies: ["AnigmaCore", "DatabaseCore", "ExecutionCore", "GovernanceCore", "StorageCore", "TelemetryCore", "ContractsCore", "MLWorkerCommon", "AnigmaPrimitives", "AnigmaMCPModule", "TextChunkingCapsule", "LayoutEngineCapsule", "VectorCapsule", "CompressionKit", "RLMModule", "VectorIndexCapsule", "ContextumModule", "InferenceCore", .product(name: "Hummingbird", package: "hummingbird"), .product(name: "HummingbirdTLS", package: "hummingbird"), .product(name: "SwiftTreeSitter", package: "swift-tree-sitter")], path: "Packages/AnigmaDaemonCore", swiftSettings: strictConcurrencySettings),
        .target(name: "MLWorkerCommon", dependencies: ["ContractsCore", .product(name: "ArgumentParser", package: "swift-argument-parser"), .product(name: "MLXLMCommon", package: "mlx-swift-lm"), .product(name: "MLXEmbedders", package: "mlx-swift-lm")], path: "Packages/MLWorkerCommon", swiftSettings: strictConcurrencySettings),
        .target(name: "TechDebtAudit", dependencies: [], path: "Packages/TechDebtAudit", swiftSettings: strictConcurrencySettings),
        .target(name: "PlatformCore", dependencies: ["AnigmaCore", "CapabilityCore", "ContractsCore"], path: "Packages/PlatformCore", swiftSettings: strictConcurrencySettings),
        .target(
            name: "AnigmaMCPModule",
            dependencies: [
                "AnigmaCore",
                "AnigmaPrimitives",
                "ContractsCore",
                "HarmoniaModule",
                "AccessumModule",
                "DiaplasionModule",
                "OutlineumModule",
                "PolytroposModule",
                "ContextumModule",
                "ArtifactStoreModule",
                "ModelRegistryModule",
                "MLWorkerCommon",
                "ModelRegistry",
                "ObservatoriumModule",
                "CathedralModule",
                "DatabaseCore",
                .product(name: "MCP", package: "swift-sdk")
            ],
            path: "Sources/AnigmaMCPModule",
            swiftSettings: strictConcurrencySettings
        ),
        .executableTarget(
            name: "AnigmaMCPExecutable",
            dependencies: [
                "AnigmaMCPModule",
                .product(name: "MCP", package: "swift-sdk")
            ],
            path: "Sources/AnigmaMCPExecutable",
            swiftSettings: strictConcurrencySettings
        ),
        .target(
            name: "RuntimeOrchestrator",
            dependencies: ["AnigmaNativeShims", "NativeKernel"],
            path: "Sources/RuntimeOrchestrator",
            swiftSettings: strictConcurrencySettings + debugPerformanceSettings
        ),
        .target(
            name: "PlatformAdapters",
            dependencies: ["RuntimeOrchestrator", "AnigmaNativeShims"],
            path: "Sources/PlatformAdapters",
            swiftSettings: strictConcurrencySettings + debugPerformanceSettings
        ),
        .target(
            name: "AnigmaUI",
            dependencies: ["PlatformAdapters", "RuntimeOrchestrator"],
            path: "Sources/AnigmaUI",
            swiftSettings: strictConcurrencySettings + debugPerformanceSettings
        ),
        .target(name: "AnigmaTestSupport", dependencies: ["AnigmaCore", "AnigmaPrimitives", "ContractsCore", "DatabaseCore", "PolytroposModule"], path: "Packages/AnigmaTestSupport", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "DatabaseCoreTests", dependencies: ["DatabaseCore", "ContractsCore"], path: "Tests/DatabaseCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCoreTests", dependencies: ["AnigmaCore", "DatabaseCore", "ContractsCore", "AnigmaTestSupport"], path: "Tests/AnigmaCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "DiaplasionModuleTests", dependencies: ["AnigmaCore", "DiaplasionModule"], path: "Tests/DiaplasionModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "PraxisCoreTests", dependencies: ["PraxisCore", "PraxisModule"], path: "Tests/PraxisCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "OutlineumModuleTests", dependencies: ["AnigmaCore", "OutlineumModule"], path: "Tests/OutlineumModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "PragmaModuleTests", dependencies: ["AnigmaCore", "PragmaModule"], path: "Tests/PragmaModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ConexusModuleTests", dependencies: ["AnigmaCore", "ConexusModule"], path: "Tests/ConexusModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "CodexModuleTests", dependencies: ["AnigmaCore", "CodexModule"], path: "Tests/CodexModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "TranscriptumModuleTests", dependencies: ["AnigmaCore", "TranscriptumModule"], path: "Tests/TranscriptumModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ObservatoriumModuleTests", dependencies: ["AnigmaCore", "ObservatoriumModule"], path: "Tests/ObservatoriumModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AccessumModuleTests", dependencies: ["AnigmaCore", "AccessumModule"], path: "Tests/AccessumModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "PolytroposModuleTests", dependencies: ["AnigmaCore", "PolytroposModule", "AnigmaTestSupport"], path: "Tests/PolytroposModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "TelemetryCoreTests", dependencies: ["TelemetryCore"], path: "Tests/TelemetryCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ExecutionCoreTests", dependencies: ["ExecutionCore"], path: "Tests/ExecutionCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "PlatformCoreTests", dependencies: ["PlatformCore", "AnigmaCore", "CapabilityCore"], path: "Tests/PlatformCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "CapabilityCoreTests", dependencies: ["CapabilityCore"], path: "Tests/CapabilityCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ContractsCoreTests", dependencies: ["ContractsCore"], path: "Tests/ContractsCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "StorageCoreTests", dependencies: ["StorageCore", "DatabaseCore", "AnigmaCore", "GovernanceCore"], path: "Tests/StorageCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "HarmoniaCLITests", dependencies: ["HarmoniaCLI", "StorageCore", "HarmoniaModule", "DatabaseCore", "AnigmaPrimitives"], path: "Tests/HarmoniaCLITests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "HarmoniaModuleTests", dependencies: ["HarmoniaModule", "AnigmaCore", "DatabaseCore"], path: "Tests/HarmoniaModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaDaemonTests", dependencies: ["AnigmaDaemonCore", "AnigmaTestSupport", "StorageCore", "TelemetryCore", .product(name: "GRPCCore", package: "grpc-swift"), .product(name: "Numerics", package: "swift-numerics")], path: "Tests/AnigmaDaemonTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "NegativeCompilationTests", dependencies: ["AnigmaClientKit"], path: "Tests/NegativeCompilationTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "CapsuleCoreTests", dependencies: ["CapsuleCore", "AnigmaPrimitives", "AnigmaNativeShims"], path: "Tests/CapsuleCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaSystemSpineTests", dependencies: ["AnigmaSystemSpine"], path: "Tests/AnigmaSystemSpineTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "DataEngineTests", dependencies: ["DataEngine", "DataCore"], path: "Tests/DataEngineTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ContextumModuleTests", dependencies: ["ContextumModule", "DatabaseCore"], path: "Tests/ContextumModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ModelDeterminismTests", dependencies: ["ModelRegistry", "ContractsCore"], path: "Tests/ModelDeterminismTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCorporateTests", dependencies: ["AnigmaCorporate", "AnigmaCore", "AnigmaSystemSpine"], path: "Tests/AnigmaCorporateTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaEducationTests", dependencies: ["AnigmaEducation"], path: "Tests/AnigmaEducationTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "GovernanceCoreTests", dependencies: ["GovernanceCore", "DatabaseCore", "AnigmaCore"], path: "Tests/GovernanceCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaAgentsTests", dependencies: ["AnigmaAgents", "AnigmaCore"], path: "Tests/AnigmaAgentsTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaGeminiBridgeTests", dependencies: ["AnigmaGeminiBridge"], path: "Tests/AnigmaGeminiBridgeTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "DocumentRenderKitTests", dependencies: ["DocumentRenderKit"], path: "Tests/DocumentRenderKitTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCLICoreTests", dependencies: ["AnigmaCLICore"], path: "Tests/AnigmaCLICoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCLIDatabaseTests", dependencies: ["AnigmaCLIDatabase", "AnigmaCLICore"], path: "Tests/AnigmaCLIDatabaseTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCLIOrchestratorTests", dependencies: ["AnigmaCLIOrchestrator", "AnigmaCLICore"], path: "Tests/AnigmaCLIOrchestratorTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCLIProvidersTests", dependencies: ["AnigmaCLIProviders"], path: "Tests/AnigmaCLIProvidersTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCLIRouterTests", dependencies: ["AnigmaCLIRouter"], path: "Tests/AnigmaCLIRouterTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCLIGovernanceTests", dependencies: ["AnigmaCLIGovernance"], path: "Tests/AnigmaCLIGovernanceTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCLIEventingTests", dependencies: ["AnigmaCLIEventing"], path: "Tests/AnigmaCLIEventingTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCLIMCPTests", dependencies: ["AnigmaCLIMCP"], path: "Tests/AnigmaCLIMCPTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaCLITests", dependencies: ["AnigmaCLIDatabase", "AnigmaCLICore", "AnigmaCLIOrchestrator"], path: "Tests/AnigmaCLITests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "CathedralModuleTests", dependencies: ["CathedralModule", "AnigmaCore", "DatabaseCore"], path: "Tests/CathedralModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ArtifactStoreModuleTests", dependencies: ["ArtifactStoreModule", "AnigmaCore", "ContractsCore", "DatabaseCore"], path: "Tests/ArtifactStoreModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ModelRegistryModuleTests", dependencies: ["ModelRegistryModule", "AnigmaCore", "ContractsCore", "DatabaseCore"], path: "Tests/ModelRegistryModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaPrimitivesTests", dependencies: ["AnigmaPrimitives"], path: "Tests/AnigmaPrimitivesTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "DataCoreTests", dependencies: ["DataCore", "AnigmaPrimitives"], path: "Tests/DataCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "VectorumModuleTests", dependencies: ["VectorumModule", "AnigmaCore", "DatabaseCore"], path: "Tests/VectorumModuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "SecurityEventsManagerTests", dependencies: ["SecurityEventsManager", "AnigmaPrimitives"], path: "Tests/SecurityEventsManagerTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnigmaClientKitTests", dependencies: ["AnigmaClientKit", "AnigmaPrimitives", "ContractsCore"], path: "Tests/AnigmaClientKitTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "MLWorkerCommonTests", dependencies: ["MLWorkerCommon", "AnigmaPrimitives"], path: "Tests/MLWorkerCommonTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "DoctrineCoreTests", dependencies: ["DoctrineCore", "GovernanceCore", "AnigmaCore", "AnigmaPrimitives"], path: "Tests/DoctrineCoreTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "HarmoniaMemoryTests", dependencies: ["HarmoniaMemory", "AnigmaCore", "TelemetryCore"], path: "Tests/HarmoniaMemoryTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "HarmoniaSurfaceTests", dependencies: ["HarmoniaSurface"], path: "Tests/HarmoniaSurfaceTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "DoctrineCLITests", dependencies: ["DoctrineCLI"], path: "Tests/DoctrineCLITests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "DiaplasionPipelineTests", dependencies: ["DiaplasionPipeline"], path: "Tests/DiaplasionPipelineTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ObservabilityKitTests", dependencies: ["ObservabilityKit"], path: "Tests/ObservabilityKitTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "CompressionKitTests", dependencies: ["CompressionKit"], path: "Tests/CompressionKitTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "TypographyKitTests", dependencies: ["TypographyKit"], path: "Tests/TypographyKitTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "AnimationKitTests", dependencies: ["AnimationKit"], path: "Tests/AnimationKitTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ColorKitTests", dependencies: ["ColorKit"], path: "Tests/ColorKitTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "ContainerKitTests", dependencies: ["ContainerKit"], path: "Tests/ContainerKitTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "CanonicalTokenizerTests", dependencies: ["CanonicalTokenizer"], path: "Tests/CanonicalTokenizerTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "LayoutEngineCapsuleTests", dependencies: ["LayoutEngineCapsule", "CapsuleCore"], path: "Tests/LayoutEngineCapsuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "VizAggregationCapsuleTests", dependencies: ["VizAggregationCapsule", "CapsuleCore"], path: "Tests/VizAggregationCapsuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "MFCTests", dependencies: ["MediaFingerprintCapsule"], path: "Tests/MFCTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "VectorCapsuleTests", dependencies: ["VectorCapsule", "CapsuleCore"], path: "Tests/VectorCapsuleTests", swiftSettings: strictConcurrencySettings),
        .testTarget(name: "EmbeddingStabilityTests", dependencies: ["ContractsCore", "VectorumModule"], path: "Tests/EmbeddingStability", swiftSettings: strictConcurrencySettings)
    ],
    cxxLanguageStandard: .cxx17
)
