//
//  InspirationStateStore.swift
//  HarmoniaModuleExperimental
//
//  HarmoniaModule/Inspiration
//
//  Stores pipeline state and task definitions.
//

import Foundation
import SQLite3
import HarmoniaModule

/// State of the inspiration pipeline.
public struct InspirationPipelineState: Sendable, Codable {
    public let id: UUID
    public let lastPatternCheck: Date
    public let pendingProposalCount: Int
    public let implementedProposalCount: Int
    public let blockedProposalCount: Int
    public let lastTaskGeneration: Date?

    public init(
        id: UUID = UUID(),
        lastPatternCheck: Date = Date(),
        pendingProposalCount: Int = 0,
        implementedProposalCount: Int = 0,
        blockedProposalCount: Int = 0,
        lastTaskGeneration: Date? = nil
    ) {
        self.id = id
        self.lastPatternCheck = lastPatternCheck
        self.pendingProposalCount = pendingProposalCount
        self.implementedProposalCount = implementedProposalCount
        self.blockedProposalCount = blockedProposalCount
        self.lastTaskGeneration = lastTaskGeneration
    }
}

/// Task generated by the inspiration pipeline.
public struct InspirationTask: Sendable, Codable {
    public let id: UUID
    public let proposalId: UUID
    public let taskType: TaskType
    public let description: String
    public let targetComponent: String
    public let priority: PatternProposal.Priority
    public let status: TaskStatus
    public let createdAt: Date
    public let startedAt: Date?
    public let completedAt: Date?
    public let errorMessage: String?

    public enum TaskType: String, Codable, Sendable {
        case implementRule = "implement_rule"
        case refactorCode = "refactor_code"
        case addService = "add_service"
        case updateArchitecture = "update_architecture"
        case optimizePerformance = "optimize_performance"
        case addDocumentation = "add_documentation"
        case addTests = "add_tests"
    }

    public enum TaskStatus: String, Codable, Sendable {
        case pending = "pending"
        case inProgress = "in_progress"
        case completed = "completed"
        case failed = "failed"
        case cancelled = "cancelled"
    }

    public init(
        id: UUID = UUID(),
        proposalId: UUID,
        taskType: TaskType,
        description: String,
        targetComponent: String,
        priority: PatternProposal.Priority = .medium,
        status: TaskStatus = .pending,
        createdAt: Date = Date(),
        startedAt: Date? = nil,
        completedAt: Date? = nil,
        errorMessage: String? = nil
    ) {
        self.id = id
        self.proposalId = proposalId
        self.taskType = taskType
        self.description = description
        self.targetComponent = targetComponent
        self.priority = priority
        self.status = status
        self.createdAt = createdAt
        self.startedAt = startedAt
        self.completedAt = completedAt
        self.errorMessage = errorMessage
    }
}

/// Database operations for inspiration pipeline state.
public actor InspirationStateStore {
    private var db: OpaquePointer?

    public init(dbPath: String = "harmonia_harness.sqlite") throws {
        if sqlite3_open(dbPath, &db) != SQLITE_OK {
            throw NSError(domain: "SQLite", code: 1, userInfo: [
                NSLocalizedDescriptionKey: "Failed to open database: \(String(cString: sqlite3_errmsg(db)))"
            ])
        }
        try createTables()
    }

    deinit {
        if let db = db {
            sqlite3_close(db)
        }
    }

    private func createTables() throws {
        let createStateTable = """
        CREATE TABLE IF NOT EXISTS inspiration_pipeline_state (
            id TEXT PRIMARY KEY,
            last_pattern_check TEXT NOT NULL,
            pending_proposal_count INTEGER NOT NULL,
            implemented_proposal_count INTEGER NOT NULL,
            blocked_proposal_count INTEGER NOT NULL,
            last_task_generation TEXT
        )
        """

        let createTasksTable = """
        CREATE TABLE IF NOT EXISTS inspiration_tasks (
            id TEXT PRIMARY KEY,
            proposal_id TEXT NOT NULL,
            task_type TEXT NOT NULL,
            description TEXT NOT NULL,
            target_component TEXT NOT NULL,
            priority INTEGER NOT NULL,
            status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            started_at TEXT,
            completed_at TEXT,
            error_message TEXT,
            FOREIGN KEY (proposal_id) REFERENCES pattern_proposals(id) ON DELETE CASCADE
        )
        """

        try executeSQL(createStateTable)
        try executeSQL(createTasksTable)

        // Initialize default state if not exists
        try initializeDefaultState()
    }

    private func executeSQL(_ sql: String) throws {
        guard let db = db else { throw NSError(domain: "SQLite", code: 2, userInfo: [NSLocalizedDescriptionKey: "Database not open"]) }

        var error: UnsafeMutablePointer<Int8>?
        if sqlite3_exec(db, sql, nil, nil, &error) != SQLITE_OK {
            let errorMsg = error.map { String(cString: $0) } ?? "Unknown error"
            sqlite3_free(error)
            throw NSError(domain: "SQLite", code: 3, userInfo: [NSLocalizedDescriptionKey: errorMsg])
        }
    }

    private func initializeDefaultState() throws {
        let checkSQL = "SELECT COUNT(*) FROM inspiration_pipeline_state"
        guard let db = db else { return }

        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, checkSQL, -1, &stmt, nil) == SQLITE_OK else {
            throw NSError(domain: "SQLite", code: 4, userInfo: [
                NSLocalizedDescriptionKey: String(cString: sqlite3_errmsg(db))
            ])
        }
        defer { sqlite3_finalize(stmt) }

        guard sqlite3_step(stmt) == SQLITE_ROW else {
            return
        }

        let count = sqlite3_column_int(stmt, 0)
        if count == 0 {
            let defaultState = InspirationPipelineState()
            try saveState(defaultState)
        }
    }

    // MARK: - State Operations

    public func saveState(_ state: InspirationPipelineState) throws {
        let sql = """
        INSERT OR REPLACE INTO inspiration_pipeline_state
        (id, last_pattern_check, pending_proposal_count, implemented_proposal_count, blocked_proposal_count, last_task_generation)
        VALUES (?, ?, ?, ?, ?, ?)
        """

        let dateFormatter = ISO8601DateFormatter()
        let lastPatternCheck = dateFormatter.string(from: state.lastPatternCheck)
        let lastTaskGeneration = state.lastTaskGeneration.map { dateFormatter.string(from: $0) }

        try executePrepared(sql, bindings: [
            state.id.uuidString,
            lastPatternCheck,
            state.pendingProposalCount,
            state.implementedProposalCount,
            state.blockedProposalCount,
            lastTaskGeneration ?? NSNull()
        ])
    }

    public func getState() throws -> InspirationPipelineState {
        let sql = "SELECT * FROM inspiration_pipeline_state LIMIT 1"

        if let result = try querySingle(sql, parser: { stmt in
            try parseState(from: stmt)
        }) {
            return result
        } else {
            // Create default state if not found
            let defaultState = InspirationPipelineState()
            try saveState(defaultState)
            return defaultState
        }
    }

    public func updateState(
        lastPatternCheck: Date? = nil,
        pendingProposalCount: Int? = nil,
        implementedProposalCount: Int? = nil,
        blockedProposalCount: Int? = nil,
        lastTaskGeneration: Date? = nil
    ) throws {
        let currentState = try getState()

        let updatedState = InspirationPipelineState(
            id: currentState.id,
            lastPatternCheck: lastPatternCheck ?? currentState.lastPatternCheck,
            pendingProposalCount: pendingProposalCount ?? currentState.pendingProposalCount,
            implementedProposalCount: implementedProposalCount ?? currentState.implementedProposalCount,
            blockedProposalCount: blockedProposalCount ?? currentState.blockedProposalCount,
            lastTaskGeneration: lastTaskGeneration ?? currentState.lastTaskGeneration
        )

        try saveState(updatedState)
    }

    // MARK: - Task Operations

    public func saveTask(_ task: InspirationTask) throws {
        let sql = """
        INSERT OR REPLACE INTO inspiration_tasks
        (id, proposal_id, task_type, description, target_component, priority, status, created_at, started_at, completed_at, error_message)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """

        let dateFormatter = ISO8601DateFormatter()
        let createdAt = dateFormatter.string(from: task.createdAt)
        let startedAt = task.startedAt.map { dateFormatter.string(from: $0) }
        let completedAt = task.completedAt.map { dateFormatter.string(from: $0) }

        try executePrepared(sql, bindings: [
            task.id.uuidString,
            task.proposalId.uuidString,
            task.taskType.rawValue,
            task.description,
            task.targetComponent,
            task.priority.rawValue,
            task.status.rawValue,
            createdAt,
            startedAt ?? NSNull(),
            completedAt ?? NSNull(),
            task.errorMessage ?? NSNull()
        ])
    }

    public func getTask(byId id: UUID) throws -> InspirationTask? {
        let sql = "SELECT * FROM inspiration_tasks WHERE id = ?"
        return try querySingle(sql, bindings: [id.uuidString]) { stmt in
            try parseTask(from: stmt)
        }
    }

    public func getTasks(byStatus status: InspirationTask.TaskStatus? = nil) throws -> [InspirationTask] {
        var sql = "SELECT * FROM inspiration_tasks"
        var bindings: [Any] = []

        if let status = status {
            sql += " WHERE status = ?"
            bindings.append(status.rawValue)
        }

        sql += " ORDER BY priority DESC, created_at ASC"

        return try queryMultiple(sql, bindings: bindings) { stmt in
            try parseTask(from: stmt)
        }
    }

    public func getPendingTasks() throws -> [InspirationTask] {
        return try getTasks(byStatus: .pending)
    }

    public func updateTaskStatus(
        _ taskId: UUID,
        status: InspirationTask.TaskStatus,
        errorMessage: String? = nil
    ) throws {
        guard let task = try getTask(byId: taskId) else {
            throw NSError(domain: "InspirationStateStore", code: 1, userInfo: [
                NSLocalizedDescriptionKey: "Task not found: \(taskId)"
            ])
        }

        let startedAt = status == .inProgress && task.startedAt == nil ? Date() : task.startedAt
        let completedAt = (status == .completed || status == .failed) && task.completedAt == nil ? Date() : task.completedAt

        let updatedTask = InspirationTask(
            id: task.id,
            proposalId: task.proposalId,
            taskType: task.taskType,
            description: task.description,
            targetComponent: task.targetComponent,
            priority: task.priority,
            status: status,
            createdAt: task.createdAt,
            startedAt: startedAt,
            completedAt: completedAt,
            errorMessage: errorMessage ?? task.errorMessage
        )

        try saveTask(updatedTask)
    }

    // MARK: - Helper Methods

    private func executePrepared(_ sql: String, bindings: [Any]) throws {
        guard let db = db else { throw NSError(domain: "SQLite", code: 2, userInfo: [NSLocalizedDescriptionKey: "Database not open"]) }

        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK else {
            throw NSError(domain: "SQLite", code: 4, userInfo: [
                NSLocalizedDescriptionKey: String(cString: sqlite3_errmsg(db))
            ])
        }
        defer { sqlite3_finalize(stmt) }

        for (index, binding) in bindings.enumerated() {
            let idx = Int32(index + 1)

            if binding is NSNull {
                sqlite3_bind_null(stmt, idx)
            } else if let string = binding as? String {
                sqlite3_bind_text(stmt, idx, string, -1, nil)
            } else if let int = binding as? Int {
                sqlite3_bind_int(stmt, idx, Int32(int))
            } else if let int64 = binding as? Int64 {
                sqlite3_bind_int64(stmt, idx, int64)
            } else if let double = binding as? Double {
                sqlite3_bind_double(stmt, idx, double)
            } else {
                sqlite3_bind_null(stmt, idx)
            }
        }

        if sqlite3_step(stmt) != SQLITE_DONE {
            throw NSError(domain: "SQLite", code: 5, userInfo: [
                NSLocalizedDescriptionKey: String(cString: sqlite3_errmsg(db))
            ])
        }
    }

    private func querySingle<T>(_ sql: String, bindings: [Any] = [], parser: (OpaquePointer) throws -> T) throws -> T? {
        guard let db = db else { throw NSError(domain: "SQLite", code: 2, userInfo: [NSLocalizedDescriptionKey: "Database not open"]) }

        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK else {
            throw NSError(domain: "SQLite", code: 4, userInfo: [
                NSLocalizedDescriptionKey: String(cString: sqlite3_errmsg(db))
            ])
        }
        defer { sqlite3_finalize(stmt) }

        for (index, binding) in bindings.enumerated() {
            let idx = Int32(index + 1)

            if binding is NSNull {
                sqlite3_bind_null(stmt, idx)
            } else if let string = binding as? String {
                sqlite3_bind_text(stmt, idx, string, -1, nil)
            } else if let int = binding as? Int {
                sqlite3_bind_int(stmt, idx, Int32(int))
            } else {
                sqlite3_bind_null(stmt, idx)
            }
        }

        guard sqlite3_step(stmt) == SQLITE_ROW else {
            return nil
        }

        return try parser(stmt!)
    }

    private func queryMultiple<T>(_ sql: String, bindings: [Any] = [], parser: (OpaquePointer) throws -> T) throws -> [T] {
        guard let db = db else { throw NSError(domain: "SQLite", code: 2, userInfo: [NSLocalizedDescriptionKey: "Database not open"]) }

        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK else {
            throw NSError(domain: "SQLite", code: 4, userInfo: [
                NSLocalizedDescriptionKey: String(cString: sqlite3_errmsg(db))
            ])
        }
        defer { sqlite3_finalize(stmt) }

        for (index, binding) in bindings.enumerated() {
            let idx = Int32(index + 1)

            if binding is NSNull {
                sqlite3_bind_null(stmt, idx)
            } else if let string = binding as? String {
                sqlite3_bind_text(stmt, idx, string, -1, nil)
            } else if let int = binding as? Int {
                sqlite3_bind_int(stmt, idx, Int32(int))
            } else {
                sqlite3_bind_null(stmt, idx)
            }
        }

        var results: [T] = []
        while sqlite3_step(stmt) == SQLITE_ROW {
            results.append(try parser(stmt!))
        }

        return results
    }

    private func parseState(from stmt: OpaquePointer) throws -> InspirationPipelineState {
        guard let id = UUID(uuidString: String(cString: sqlite3_column_text(stmt, 0))) else {
            fatalError("Failed to unwrap id")
        }

        let lastPatternCheckString = String(cString: sqlite3_column_text(stmt, 1))
        let lastPatternCheck = ISO8601DateFormatter().date(from: lastPatternCheckString) ?? Date()

        let pendingProposalCount = Int(sqlite3_column_int(stmt, 2))
        let implementedProposalCount = Int(sqlite3_column_int(stmt, 3))
        let blockedProposalCount = Int(sqlite3_column_int(stmt, 4))

        let lastTaskGeneration: Date?
        if sqlite3_column_type(stmt, 5) == SQLITE_NULL {
            lastTaskGeneration = nil
        } else {
            let lastTaskGenerationString = String(cString: sqlite3_column_text(stmt, 5))
            lastTaskGeneration = ISO8601DateFormatter().date(from: lastTaskGenerationString)
        }

        return InspirationPipelineState(
            id: id,
            lastPatternCheck: lastPatternCheck,
            pendingProposalCount: pendingProposalCount,
            implementedProposalCount: implementedProposalCount,
            blockedProposalCount: blockedProposalCount,
            lastTaskGeneration: lastTaskGeneration
        )
    }

    private func parseTask(from stmt: OpaquePointer) throws -> InspirationTask {
        guard let id = UUID(uuidString: String(cString: sqlite3_column_text(stmt, 0))) else {
            fatalError("Failed to unwrap id")
        }
        guard let proposalId = UUID(uuidString: String(cString: sqlite3_column_text(stmt, 1))) else {
            fatalError("Failed to unwrap proposalId")
        }
        guard let taskType = InspirationTask.TaskType(rawValue: String(cString: sqlite3_column_text(stmt, 2))) else {
            fatalError("Failed to unwrap taskType")
        }
        let description = String(cString: sqlite3_column_text(stmt, 3))
        let targetComponent = String(cString: sqlite3_column_text(stmt, 4))
        let priority = PatternProposal.Priority(rawValue: Int(sqlite3_column_int(stmt, 5))) ?? .medium
        guard let status = InspirationTask.TaskStatus(rawValue: String(cString: sqlite3_column_text(stmt, 6))) else {
            fatalError("Failed to unwrap status")
        }

        let createdAtString = String(cString: sqlite3_column_text(stmt, 7))
        let createdAt = ISO8601DateFormatter().date(from: createdAtString) ?? Date()

        let startedAt: Date?
        if sqlite3_column_type(stmt, 8) == SQLITE_NULL {
            startedAt = nil
        } else {
            let startedAtString = String(cString: sqlite3_column_text(stmt, 8))
            startedAt = ISO8601DateFormatter().date(from: startedAtString)
        }

        let completedAt: Date?
        if sqlite3_column_type(stmt, 9) == SQLITE_NULL {
            completedAt = nil
        } else {
            let completedAtString = String(cString: sqlite3_column_text(stmt, 9))
            completedAt = ISO8601DateFormatter().date(from: completedAtString)
        }

        let errorMessage = sqlite3_column_type(stmt, 10) == SQLITE_NULL ? nil : String(cString: sqlite3_column_text(stmt, 10))

        return InspirationTask(
            id: id,
            proposalId: proposalId,
            taskType: taskType,
            description: description,
            targetComponent: targetComponent,
            priority: priority,
            status: status,
            createdAt: createdAt,
            startedAt: startedAt,
            completedAt: completedAt,
            errorMessage: errorMessage
        )
    }
}
